all: q1 q2 q3 q4

q1:
	g++ -std=c++11 val_test01_solved.cpp -o val_test01_solved
	g++ -std=c++11 val_test02_solved.cpp -o val_test02_solved

q2:
	g++ -fopenmp -std=c++11 MMult1.cpp -o MMult1

q3:
    
	g++ -fopenmp -std=c++11 omp_solved2.c -o omp_solved2
	g++ -fopenmp -std=c++11 omp_solved3.c -o omp_solved3
	g++ -fopenmp -std=c++11 omp_solved4.c -o omp_solved4
	g++ -fopenmp -std=c++11 omp_solved5.c -o omp_solved5
	g++ -fopenmp -std=c++11 omp_solved6.c -o omp_solved6

q4:
	g++ -fopenmp -std=c++11 jacobi2D-omp.cpp -o jacobi2D-omp
	g++ -fopenmp -std=c++11 gs2D-omp.cpp -o gs2D-omp

